//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface LoginResponse {
    playerId: string;
    token: string;
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface LoginRequest {
    login: string;
}

export interface MatchResponse {
    matchId: string;
    startDate: number;
    endDate: number;
    homePlayerId: string;
    awayPlayerId: string;
}

export interface AddMatchRequest {
    startDate: number;
    endDate: number;
    homePlayerId: string;
    awayPlayerId: string;
}

export interface PlayerResponse {
    playerId: string;
    nameTag: string;
    team: string;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}