// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalanCup.Infrastructure.Database;

#nullable disable

namespace TalanCup.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TalanCupContext))]
    partial class TalanCupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TalanCup.Domain.Match", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayPlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("EndDate")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HomePlayerId")
                        .HasColumnType("uuid");

                    b.Property<long>("StartDate")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayPlayerId");

                    b.HasIndex("HomePlayerId");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("TalanCup.Domain.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TalanCup.Domain.Match", b =>
                {
                    b.HasOne("TalanCup.Domain.Player", "AwayPlayer")
                        .WithMany()
                        .HasForeignKey("AwayPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalanCup.Domain.Player", "HomePlayer")
                        .WithMany()
                        .HasForeignKey("HomePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayPlayer");

                    b.Navigation("HomePlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
